import{i as c}from"./assets/vendor-8e8cd629.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();function u(o){return fetch(`https://pixabay.com/api/?key=45098523-0f66f1bf08e0be6a1e71621a5&q=${o}&image_type=photo&orientation=horizontal&safesearch=true`).then(s=>{if(!s.ok)throw new Error(s.status);return s.json()})}const l=document.querySelector(".form-inline"),a=document.querySelector(".image-container");l.addEventListener("submit",f);function f(o){o.preventDefault();const n=o.currentTarget.elements.query.value.trim().toLowerCase();if(n===""){c.warning({title:"Warning",message:"Search query cannot be empty."});return}u(n).then(s=>{s.hits.length>0?m(s.hits):c.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"})}).catch(d).finally(()=>l.reset())}function m(o){a.innerHTML="",o.forEach(t=>{const n=document.createElement("div");n.classList.add("image-card"),n.innerHTML=`
      <img src="${t.webformatURL}" alt="${t.tags}" />
      <div class="info">
        <p><strong>Likes:</strong> ${t.likes}</p>
        <p><strong>Views:</strong> ${t.views}</p>
        <p><strong>Comments:</strong> ${t.comments}</p>
        <p><strong>Downloads:</strong> ${t.downloads}</p>
      </div>
    `,a.appendChild(n)})}function d(o){c.error({title:"Error",message:`Failed to fetch images: ${o.message}`})}
//# sourceMappingURL=commonHelpers.js.map
